---
  - name: Add standard user to sudo group.
    user:
      name: lucas
      state: present
      comment: "Standard user with sudo for lucas"
      groups: sudo
      append: yes

  - name: Add ansible standard user to sudo group.
    user:
      name: ansible
      state: present
      comment: "User for ansible automation"
      groups: sudo
      append: yes

  - name: Add standard user ssh keys.
    authorized_key:
      user: lucas
      key: "{{ item }}"
    with_items:
      - https://github.com/lucasmaurice.keys

  - name: Add ansible standard user ssh keys.
    authorized_key:
      user: ansible
      key: "{{ item }}"
    with_items:
      - https://github.com/lucasmaurice.keys

  - name: Allow privilege escalation without password.
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%sudo ALL\='
      line: '%sudo ALL=(ALL) NOPASSWD:ALL'
      validate: 'visudo -cf %s'
