---
- name: Install base packages
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes 
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - git
    - vim
    - htop
    - sudo
    - gnupg2
    - python-pip
    - python3-pip
    - gcc
    - make
    - autoconf
    - autoconf-archive
    - autogen
    - automake
    - pkg-config
    - lm-sensors
    - dstat
    - sysstat
    - snmp
    - mtr
    - ncdu
    - tcpdump
    - python-dev
    - net-tools
    - locate
    - man
    - bash-completion
    - dnsutils
    - iftop
