---
- name: Install requirements
  package:
    name: "{{ item }}"
    state: present
  loop:
    - unattended-upgrades
    - apt-listchanges

- name: Template unattended-upgrades configuration
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644
